[package]
name = "tinycom-emulator"
version = "0.0.1"
authors = ["Corwin McKnight <corwin.mcknight@gmail.com>"]

[dependencies]
tinycom-common = { path = "../tinycom-common" }
enum-primitive-derive = "^0.1"
num = "0.2"
num-traits = "^0.1"
log = "0.4"
